
name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-image
  ACR_NAME: my-acr
  ACR_REGISTRY: $ACR_NAME.azurecr.io
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: todolist-az:latest
