
name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

env:
  ACR_REGISTRY: rpacr01.azurecr.io
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: rpacr01.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
        docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}